name: Build and Test backend
run-name: ${{ github.actor }} is Building and Testing Backend
on: [push]

jobs:
  Build-and-Test:
    runs-on: unbuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Intall
        working-directory: ./backend
        run: npm ci
      - name: Build
        working-directory: ./backend
        run: npm run build
      - name: Test
        working-directory: ./backend
        run: npm run test
          